### ISSUE TITLE
[Question] A Mac Version ?

### ISSUE THREAD

**Issue by RedLeZ** [kaniol-lck/modmanager#99]
### Question Type (问题类型)

Usage (使用)

### Describe the question (描述你的问题)

Hello There, 
I was following this project recently, and i was wondering if we could have a Mac Os version of this amazing work

Thank you for reading :)

### This issue is unique (这个issue是唯一的)

- [x] I have searched the issue tracker and did not find an issue describing my question.

**Comment by kaniol-lck** [comment]
I'm fixing this project recently for some API updates, and unfortunately still busy right now, so the fixing progress might be slow and from time to time. Besides, I do not have a Mac machine, so i suspended the mac build in github ci previously.
The code itself is completely compatible for mac, you can build it yourself if you want, with just resloving *quazip* and *aria2* dependencies. Otherwise i would try my best to build it in some day <3

**Comment by RedLeZ** [comment]
Sorry for answering late.. :(
Thank you so much for answering my question !
and yeah i would compile it no problem, i was just asking for the umm.. like the officiel support if you know what i mean. i would be happy to find a mac version one day for this project. 

Thanks again for answering my question i would be happy to see this project bloom more 👍 💯

**Comment by kaniol-lck** [comment]
Done in the latest [pre-release](https://github.com/kaniol-lck/modmanager/releases/tag/v1.1.1-build.636) , have a try plz, though i dont know whether it actually works or not.

**Comment by RedLeZ** [comment]
sure

**Comment by kaniol-lck** [comment]
"dyld error", i guess something got wrong with linking dynamic libs, i would try to fix packaging

**Comment by kaniol-lck** [comment]
`___asan_option_detect_stack_use_after_return` in libaria2 caused this problem, now i disabled it, so it should work.

**Comment by RedLeZ** [comment]
And it works THX you .
